# Java 21 runtime
FROM eclipse-temurin:21-jre-alpine

WORKDIR /app

# Copy the Spring Boot fat jar
COPY target/*.jar app.jar

# Render provides PORT, Spring already handles it
EXPOSE 8080

# Run the app
ENTRYPOINT ["java", "-jar", "app.jar"]
